### ISSUE TITLE
Crash while in inventory when hovering over item with gem

### ISSUE THREAD

**Issue by Revelates** [Daripher/Passive-Skill-Tree#11]
[crash-2023-07-16_17.51.48-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/12065392/crash-2023-07-16_17.51.48-client.txt)

**Comment by FocusNIL** [comment]
Can second this, but mine never fully crashes, just goes into infinite loading. Here is the relevant snippet from the log:
<details><summary>Snippet</summary>
<p>

[19:46:56] [Render thread/ERROR]: Exception caught during firing event: Cannot invoke "daripher.skilltree.item.gem.GemItem.getName(net.minecraft.world.item.ItemStack)" because "gem" is null
	Index: 16
	Listeners:
		0: HIGHEST
		1: ASM: class ovh.corail.tombstone.event.ClientEventHandler handleTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		2: ASM: class com.obscuria.aquamirae.AquamiraeClient$ForgeEvents fixOldPerk(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		3: HIGH
		4: ASM: class dev.architectury.event.forge.EventHandlerImplClient event(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		5: ASM: class daripher.skilltree.attribute.AttributeBonusHandler addPoisonedWeaponTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		6: NORMAL
		7: ASM: class caittastic.homespun.events.CoreClientEvents handleItemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		8: net.minecraftforge.eventbus.EventBus$$Lambda$1470/0x0000000800797140@951cb29
		9: net.minecraftforge.eventbus.EventBus$$Lambda$1470/0x0000000800797140@1ec46ac6
		10: ASM: class vectorwing.farmersdelight.client.event.TooltipEvents addTooltipToVanillaSoups(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		11: net.minecraftforge.eventbus.EventBus$$Lambda$1470/0x0000000800797140@50fb71a1
		12: ASM: class com.verdantartifice.primalmagick.client.events.ClientRenderEvents renderTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		13: net.minecraftforge.eventbus.EventBus$$Lambda$1470/0x0000000800797140@3d210b26
		14: ASM: class com.mlib.itemsets.ItemSetTooltip onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		15: ASM: class com.mlib.gamemodifiers.contexts.OnItemTooltip onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		16: ASM: class daripher.skilltree.gem.GemBonusHandler addGemstoneTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		17: ASM: class cofh.core.event.CoreClientEvents handleItemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		18: ASM: class net.bettercombat.forge.events.ForgeClientEvents onToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		19: ASM: class daripher.skilltree.attribute.AttributeBonusHandler addFoodBonusesTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		20: ASM: class daripher.skilltree.attribute.AttributeBonusHandler addAdditionalSocketTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		21: ASM: net.brnbrd.delightful.common.ForgeEvents@38d1fcb0 onPieTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		22: ASM: class com.teammetallurgy.aquaculture.loot.FishWeightHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		23: ASM: class com.teammetallurgy.aquaculture.misc.AquaTooltip onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		24: ASM: class twilightforest.client.TFClientEvents tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		25: ASM: class twilightforest.client.TFClientEvents translateBookAuthor(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		26: ASM: class com.github.klikli_dev.occultism.handlers.TooltipHandler onAddInformation(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		27: ASM: class net.mcreator.undead_unleashed.procedures.GraveMetalArmorTooltipsProcedure onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		28: ASM: class io.redspace.ironsspellbooks.player.ClientPlayerEvents imbuedWeaponTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		29: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ClientEventsForge itemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		30: ASM: vazkii.quark.content.building.module.CelebratoryLampsModule@90dbeab onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		31: ASM: vazkii.quark.content.tweaks.module.GoldToolsHaveFortuneModule@13b7a133 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		32: ASM: class vazkii.quark.base.client.handler.RequiredModTooltipHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		33: net.minecraftforge.eventbus.EventBus$$Lambda$1470/0x0000000800797140@3aae9728
		34: ASM: class com.simibubi.create.foundation.events.ClientEvents addToItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		35: ASM: top.theillusivec4.curios.client.ClientEventHandler@1493f02d onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		36: ASM: com.github.mechalopa.hmag.client.ModClientEvents@35395de4 addItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		37: ASM: shetiphian.multibeds.client.misc.EventHandlerClient@10962972 itemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		38: LOW
		39: net.minecraftforge.eventbus.EventBus$$Lambda$1470/0x0000000800797140@70158e1
		40: LOWEST
		41: ASM: class com.endertech.minecraft.forge.client.DevInfo onInventoryTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		42: net.minecraftforge.eventbus.EventBus$$Lambda$1470/0x0000000800797140@c7c57d9
java.lang.NullPointerException: Cannot invoke "daripher.skilltree.item.gem.GemItem.getName(net.minecraft.world.item.ItemStack)" because "gem" is null
	at TRANSFORMER/skilltree@0.4.9b/daripher.skilltree.gem.GemBonusHandler.addGemTooltip(GemBonusHandler.java:148)
	at TRANSFORMER/skilltree@0.4.9b/daripher.skilltree.gem.GemBonusHandler.addGemstoneTooltips(GemBonusHandler.java:65)
	at TRANSFORMER/skilltree@0.4.9b/daripher.skilltree.gem.__GemBonusHandler_addGemstoneTooltips_ItemTooltipEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.14/net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:257)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:782)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.gui.screens.Screen.m_96555_(Screen.java:193)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.gui.screens.Screen.m_6057_(Screen.java:170)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_7025_(AbstractContainerScreen.java:173)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.gui.screens.inventory.InventoryScreen.m_6305_(InventoryScreen.java:84)
	at TRANSFORMER/forge@43.2.14/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:441)
	at TRANSFORMER/forge@43.2.14/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:434)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.14/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

[19:46:57] [Server thread/INFO]: stop local service
[19:46:57] [Server thread/INFO]: Stopping server
[19:46:57] [Server thread/INFO]: Saving players
[19:46:57] [Server thread/INFO]: FocusNIL lost connection: Disconnected
[19:46:57] [Server thread/INFO]: FocusNIL left the game
[19:46:57] [Server thread/INFO]: Stopping singleplayer server as player logged out
[19:46:57] [Server thread/INFO]: Saving worlds
[19:46:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Unskilled]'/minecraft:overworld
[19:46:58] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Unskilled]'/minecraft:the_end
[19:46:58] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Unskilled]'/minecraft:the_nether
[19:46:58] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Unskilled]'/twilightforest:twilight_forest
[19:46:58] [Server thread/INFO]: ThreadedAnvilChunkStorage (Unskilled): All chunks are saved
[19:46:58] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19:46:58] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:46:58] [Server thread/INFO]: ThreadedAnvilChunkStorage (twilight_forest): All chunks are saved
[19:46:58] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

</p>
</details> 

For added information, I was able to hover over enchanted items without a crash, so that appears to be fixed, it was just the axe with a socketed gem that caused the issue. 

EDIT: Version number is 1.19.2-BETA-0.4.9b, since it looks like there may have been a replacement file for this version pushed up, I updated  just before this post.
