### ISSUE TITLE
Cannot open game with Apotheosis

### ISSUE THREAD

**Issue by hhhhhge** [Daripher/Passive-Skill-Tree#231]
[错误报告-2024-7-15_19.10.58.zip](https://github.com/user-attachments/files/16233563/-2024-7-15_19.10.58.zip)

**Comment by Raresheky2227** [comment]
Having the same problem here.
https://github.com/Shadows-of-Fire/Apotheosis/issues/1300.

**Comment by Neglevin** [comment]
also having the same issue: 
https://pastebin.com/sf5eT1Bt

**Comment by TSWill03** [comment]
Version of the mod with the issue resolved: the socket folder was removed from the affix, causing a 'class not found' error. Just to clarify, I translated this with ChatGPT because my English is very poor. Just download the file and replace it with your passive.
https://drive.google.com/file/d/1MrF-TgJ2Hn8gNtCKulDzQ5ROv2s6nZIn/view?usp=drive_link

**Comment by Krimatoria** [comment]
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Suspected Mod: 
> 	Drippy Loading Screen (drippyloadingscreen), Version: 3.0.1
> 		Mixin class: de.keksuccino.drippyloadingscreen.mixin.mixins.forge.client.MixinForgeLoadingOverlay
> 		Target: net.minecraftforge.client.loading.ForgeLoadingOverlay
> 		at TRANSFORMER/forge@47.3.0/net.minecraftforge.client.loading.ForgeLoadingOverlay.handler$emj000$drippyloadingscreen$cancelForgeCustomLoadingOverlayRenderingDrippy(ForgeLoadingOverlay.java:1027)
> Stacktrace:
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[Connector-1.0.0-beta.44+1.20.1.jar%23482%23486!/:0.12.11+mixin.0.8.5] {}
> -- MOD apotheosis --
> Details:
> 	Caused by 0: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 		at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 		at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 		at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {}
> 		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {}
> 		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
> 		at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
> 		at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
> 		at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
> 		at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
> 		at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
> 		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
> 		at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
> 		at java.lang.Class.getDeclaringClass0(Native Method) ~[?:?] {re:mixin}
> 		at java.lang.Class.isTopLevelClass(Unknown Source) ~[?:?] {re:mixin}
> 		at java.lang.Class.getSimpleBinaryName(Unknown Source) ~[?:?] {re:mixin}
> 		at java.lang.Class.getSimpleName0(Unknown Source) ~[?:?] {re:mixin}
> 		at java.lang.Class.getSimpleName(Unknown Source) ~[?:?] {re:mixin}
> 		at net.minecraftforge.eventbus.IEventListenerFactory.getUniqueName(IEventListenerFactory.java:14) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 		at net.minecraftforge.eventbus.ModLauncherFactory.enqueueWrapper(ModLauncherFactory.java:23) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 		at net.minecraftforge.eventbus.ModLauncherFactory.createWrapper(ModLauncherFactory.java:17) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 		at net.minecraftforge.eventbus.ClassLoaderFactory.create(ClassLoaderFactory.java:25) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 		at net.minecraftforge.eventbus.ASMEventHandler.<init>(ASMEventHandler.java:37) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:267) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 		at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:163) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 		at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:86) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?] {}
> 		at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
> 		at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
> 		at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
> 		at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
> 		at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
> 		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}
> 		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}
> 		at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
> 		at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}
> 		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:86) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.20.1-47.3.0.jar%23842!/:?] {}
> 		at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {re:mixin}
> 		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.20.1-47.3.0.jar%23842!/:?] {}
> 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:85) ~[javafmllanguage-1.20.1-47.3.0.jar%23842!/:?] {}
> 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23841!/:?] {re:mixin}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}
> 
> 	Mod File: /C:/Users/Dotka/AppData/Roaming/PrismLauncher/instances/---/.minecraft/mods/Apotheosis-1.20.1-7.4.0.jar
> 	Failure message: Apotheosis (apotheosis) has failed to load correctly
> 		org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	Mod Version: 7.4.0
> 	Mod Issue URL: NOT PROVIDED
> 	Exception message: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector showPlayerSockets(Lnet/minecraft/world/item/ItemStack;)Ljava/util/List; in skilltree.mixins.json:apotheosis/AdventureModuleClientMixin from mod skilltree failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap skilltree.refmap.json
> Stacktrace:
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {}
> 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
> 	at java.lang.Class.getDeclaringClass0(Native Method) ~[?:?] {re:mixin}
> 	at java.lang.Class.isTopLevelClass(Unknown Source) ~[?:?] {re:mixin}
> 	at java.lang.Class.getSimpleBinaryName(Unknown Source) ~[?:?] {re:mixin}
> 	at java.lang.Class.getSimpleName0(Unknown Source) ~[?:?] {re:mixin}
> 	at java.lang.Class.getSimpleName(Unknown Source) ~[?:?] {re:mixin}
> 	at net.minecraftforge.eventbus.IEventListenerFactory.getUniqueName(IEventListenerFactory.java:14) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.ModLauncherFactory.enqueueWrapper(ModLauncherFactory.java:23) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.ModLauncherFactory.createWrapper(ModLauncherFactory.java:17) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.ClassLoaderFactory.create(ClassLoaderFactory.java:25) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.ASMEventHandler.<init>(ASMEventHandler.java:37) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:267) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:163) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:86) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?] {}
> 	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
> 	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
> 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
> 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}
> 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
> 	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:86) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.20.1-47.3.0.jar%23842!/:?] {}
> 	at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {re:mixin}
> 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.20.1-47.3.0.jar%23842!/:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:85) ~[javafmllanguage-1.20.1-47.3.0.jar%23842!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23841!/:?] {re:mixin}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}
> 
> 
> -- MOD skilltree --
> Details:
> 	Caused by 0: java.lang.NoClassDefFoundError: dev/shadowsoffire/apotheosis/adventure/affix/socket/gem/bonus/GemBonus
> 		at daripher.skilltree.compat.apotheosis.ApotheosisCompatibility.register(ApotheosisCompatibility.java:42) ~[PassiveSkillTree-1.20.1-BETA-0.6.13a-all.jar%23734!/:0.6.13a] {re:mixin,re:classloading,pl:redirector:A}
> 		at daripher.skilltree.SkillTreeMod.addCompatibilities(SkillTreeMod.java:51) ~[PassiveSkillTree-1.20.1-BETA-0.6.13a-all.jar%23734!/:0.6.13a] {re:classloading}
> 		at daripher.skilltree.SkillTreeMod.<init>(SkillTreeMod.java:42) ~[PassiveSkillTree-1.20.1-BETA-0.6.13a-all.jar%23734!/:0.6.13a] {re:classloading}
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
> 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23842!/:?] {}
> 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23841!/:?] {re:mixin}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}
> 
> 	Mod File: /C:/Users/Dotka/AppData/Roaming/PrismLauncher/instances/---/.minecraft/mods/PassiveSkillTree-1.20.1-BETA-0.6.13a-all.jar
> 	Failure message: Passive Skill Tree (skilltree) has failed to load correctly
> 		java.lang.NoClassDefFoundError: dev/shadowsoffire/apotheosis/adventure/affix/socket/gem/bonus/GemBonus
> 	Mod Version: 0.6.13a
> 	Mod Issue URL: NOT PROVIDED
> 	Exception message: java.lang.ClassNotFoundException: dev.shadowsoffire.apotheosis.adventure.affix.socket.gem.bonus.GemBonus
> Stacktrace:
> 	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?] {}
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
> 	at daripher.skilltree.compat.apotheosis.ApotheosisCompatibility.register(ApotheosisCompatibility.java:42) ~[PassiveSkillTree-1.20.1-BETA-0.6.13a-all.jar%23734!/:0.6.13a] {re:mixin,re:classloading,pl:redirector:A}
> 	at daripher.skilltree.SkillTreeMod.addCompatibilities(SkillTreeMod.java:51) ~[PassiveSkillTree-1.20.1-BETA-0.6.13a-all.jar%23734!/:0.6.13a] {re:classloading}
> 	at daripher.skilltree.SkillTreeMod.<init>(SkillTreeMod.java:42) ~[PassiveSkillTree-1.20.1-BETA-0.6.13a-all.jar%23734!/:0.6.13a] {re:classloading}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23842!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23841!/:?] {re:mixin}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}
>

**Comment by CapToad** [comment]
will this ever get fixed????

**Comment by Krimatoria** [comment]
> will this ever get fixed????

At least everything works for me.

**Comment by CapToad** [comment]
> > will this ever get fixed????
> 
> the new version is already in the forge At least everything works for me.

oh i thought it isnt since the issue still isnt closed mb

**Comment by Krimatoria** [comment]
> Reference in new

Ahah, you misunderstood me) I'm an ordinary player, not a developer. I had the same problem that the game wouldn't start. Everything is working now)

**Comment by Krimatoria** [comment]
> > > will this ever get fixed????
> > 
> > 
> > the new version is already in the forge At least everything works for me.
> 
> oh i thought it isnt since the issue still isnt closed mb

Ahah, you misunderstood me) I'm an ordinary player, not a developer. I had the same problem that the game wouldn't start. I don't have this error right now) I'm writing through a translator and Google translated me the wrong way)

**Comment by lemarlem** [comment]
На данный момент всё работает с таким набором версий модов PassiveSkillTree-1.20.1-BETA-0.6.14a-all , Apotheosis-1.20.1-7.4.3 , ApothicAttributes-1.20.1-1.3.5 , Placebo-1.20.1-8.6.2


At the moment everything works with this set of mod versions PassiveSkillTree-1.20.1-BETA-0.6.14a-all , Apotheosis-1.20.1-7.4.3 , ApothicAttributes-1.20.1-1.3.5 , Placebo-1.20.1-8.6.2

**Comment by ErythroCraft** [comment]
Synatra is detected! Please load Forge 47.1.3

Best way before downloading mods is reading the description of the owner.

🛠️ [Beta state notice](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector#:~:text=%F0%9F%9B%A0%EF%B8%8F-,Beta%20state%20notice,-Connector%20is%20currently)

**Comment by ErythroCraft** [comment]
Custom Connector Version can be found here

[Custom-Modversion-SyntrasConnector](https://github.com/ErythroCraft/Custom-Modversion-SyntrasConnector/releases)

**Comment by HappyBell92** [comment]
Check if your Apotheosis is up to date. I had the same error and turned out the mod pack I am playing with had an outdated Apotheosis version
