### ISSUE TITLE
Crash on joing SSP world

### ISSUE THREAD

**Issue by KatoNamus** [Daripher/Passive-Skill-Tree#35]
Hi, I've been having issues with my game crashing, eventually found another mod (Neruina) that helped me pinpoint the problem down to Passive Skill Tree. Detailed information and relevant log below (debug.log is 30MB, latest.log is about 2MB, let me know if you need it either of them (I'll zip and upload to Dropbox if you need them)).

Minecraft ver: 1.19.2
Forge ver: 43.2.21
Passive Skill Tree ver/file: `PassiveSkillTree-1.19.2-BETA-0.5.7a.jar`

Log excerpt:
```
[27Aug2023 15:53:36.070] [Server thread/WARN] [neruina/]: [Neruina]: Caught Ticking Player, KatoNamus has been kicked.
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:510) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.mixinextras$bridge$0$m_9240_(ServerGamePacketListenerImpl.java) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.wrapOperation$col000$tick(ServerGamePacketListenerImpl.java:4865) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Invalid slot 'ARMOR': 0
	at net.minecraft.world.entity.EquipmentSlot.m_20744_(EquipmentSlot.java:547) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at daripher.skilltree.attribute.AttributeBonusHandler.getMaximumLifePerGemInArmor(AttributeBonusHandler.java:268) ~[PassiveSkillTree-1.19.2-BETA-0.5.7a.jar%23891!/:0.5.7a]
	at daripher.skilltree.attribute.AttributeBonusHandler.applyDynamicAttributeBonus(AttributeBonusHandler.java:242) ~[PassiveSkillTree-1.19.2-BETA-0.5.7a.jar%23891!/:0.5.7a]
	at daripher.skilltree.attribute.AttributeBonusHandler.applyDynamicAttributeBonuses(AttributeBonusHandler.java:148) ~[PassiveSkillTree-1.19.2-BETA-0.5.7a.jar%23891!/:0.5.7a]
	at daripher.skilltree.attribute.__AttributeBonusHandler_applyDynamicAttributeBonuses_PlayerTickEvent.invoke(.dynamic) ~[PassiveSkillTree-1.19.2-BETA-0.5.7a.jar%23891!/:0.5.7a]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:814) ~[forge-1.19.2-43.2.21-universal.jar%231042!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:216) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[client-1.19.2-20220805.130853-srg.jar%231037!/:?]
	... 11 more
```

**Comment by Daripher** [comment]
For some reason armor slot with index 0 doesn't exist in your game

**Comment by KatoNamus** [comment]
Yeah, I'm about to install UniversalMinecraftEditor which I think I could use to see player data with (before I had to reinstall @#$#^%&& Windows) to see what's going on there.
It might be another mod messing around with that (450 mods in pack).

**Comment by KatoNamus** [comment]
FWIW, UniversalMCE shows them as "Slot: 100" for boots, "Slot: 101" for leggings, "Slot: 102" for chestplate and "Slot: 103" for helmet. Not sure how that would translate over to Java code though.

**Comment by Daripher** [comment]
I could rewrite that part of code but that really shouldn't happen, something is breaking your game

**Comment by KatoNamus** [comment]
I hear you and I apologize for complicating things but I would really appreciate a fix for it, please. Your mod is just too good, nay, **BRILLIANT** to not have in my pack. And of course, thank you in advance.

**Comment by KatoNamus** [comment]
My apologies. It seems I've been barking up the wrong tree again. One of my optimization mods, [Redirectionor [Modern], just updated with a suspiciously relevant changelog](https://www.curseforge.com/minecraft/mc-mods/redirectionor/files/4726220) so I updated and tested, starts up fine now. Passive Skill Tree was never to blame for this crash.
