### ISSUE TITLE
Crash when joining world

### ISSUE THREAD

**Issue by Karashok-Leo** [Daripher/Passive-Skill-Tree#45]
Crash when joining world
[crash-2023-09-16_21.50.33-server.txt](https://github.com/Daripher/Passive-Skill-Tree/files/12640846/crash-2023-09-16_21.50.33-server.txt)

**Comment by SiverDX** [comment]
Same here, happend when re-joining a world

```
[23:58:42] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.world.entity.player.Player.m_21133_(net.minecraft.world.entity.ai.attributes.Attribute)" because "player" is null
	Index: 1
	Listeners:
		0: HIGH
		1: ASM: class shadows.apotheosis.adventure.client.AdventureModuleClient tooltips(Lshadows/apotheosis/core/attributeslib/api/AddAttributeTooltipsEvent;)V
		2: NORMAL
		3: ASM: class dev.momostudios.coldsweat.util.compat.CompatManager onLivingTempDamage(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_21133_(net.minecraft.world.entity.ai.attributes.Attribute)" because "player" is null
	at TRANSFORMER/skilltree@0.5.8/daripher.skilltree.item.gem.GemHelper.getPlayerSockets(GemHelper.java:148)
	at TRANSFORMER/skilltree@0.5.8/daripher.skilltree.compat.apotheosis.ApotheosisCompatibility.getSockets(ApotheosisCompatibility.java:103)
	at TRANSFORMER/apotheosis@6.4.0/shadows.apotheosis.adventure.client.AdventureModuleClient.redirect$goi000$addPlayerSockets2(AdventureModuleClient.java:530)
	at TRANSFORMER/apotheosis@6.4.0/shadows.apotheosis.adventure.client.AdventureModuleClient.tooltips(AdventureModuleClient.java:178)
	at TRANSFORMER/apotheosis@6.4.0/shadows.apotheosis.adventure.client.__AdventureModuleClient_tooltips_AddAttributeTooltipsEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/apotheosis@6.4.0/shadows.apotheosis.core.attributeslib.client.AttributesLibClient.tooltips(AttributesLibClient.java:99)
	at TRANSFORMER/apotheosis@6.4.0/shadows.apotheosis.core.attributeslib.client.__AttributesLibClient_tooltips_ItemTooltipEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.3.0/net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:259)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:782)
	at TRANSFORMER/lootbeams@1.0/com.lootbeams.ClientSetup.lambda$onItemCreation$1(ClientSetup.java:40)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at TRANSFORMER/lootbeams@1.0/com.lootbeams.ClientSetup.onItemCreation(ClientSetup.java:40)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:79)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157592_(PersistentEntitySectionManager.java:260)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157582_(PersistentEntitySectionManager.java:259)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157506_(PersistentEntitySectionManager.java:269)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:335)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Daripher** [comment]
Does this happen with the latest version of the mod?

**Comment by Karashok-Leo** [comment]
> Does this happen with the latest version of the mod?

Yes, still happen with 0.5.8

**Comment by SiverDX** [comment]
https://github.com/Daripher/Passive-Skill-Tree/blob/c81e8cfaf0d0f802300d1416a565ab5abd6770a2/src/main/java/daripher/skilltree/compat/apotheosis/ApotheosisCompatibility.java#L103

should probably do the null check in the problematic method itself

**Comment by Baenjamin** [comment]
Still happens in 0.5.9b for 1.19.2. Not sure if it's because i've nerfed the skills in the editor. Have only nerfed like % numbers down. Nothing else. 

[crash-2023-10-10_00.31.34-server.txt](https://github.com/Daripher/Passive-Skill-Tree/files/12851002/crash-2023-10-10_00.31.34-server.txt)

[latest.log](https://github.com/Daripher/Passive-Skill-Tree/files/12851009/latest.log)
