### ISSUE TITLE
[1.19.2 - 0.5.9]: Can't join any world (Singleplayer)

### ISSUE THREAD

**Issue by SiverDX** [Daripher/Passive-Skill-Tree#47]
Keep getting disconnected with this error (happens in the `PlayerLoggedInEvent`)

``` log
[28Sep2023 17:03:10.335] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifier$Operation.ordinal()" because "operation" is null
	at daripher.skilltree.util.ByteBufHelper.writeAttributeModifier(ByteBufHelper.java:41) ~[PassiveSkillTree-1.19.2-BETA-0.5.9.jar%23725!/:0.5.9]
	at daripher.skilltree.util.ByteBufHelper.lambda$writeAttributeModifiers$1(ByteBufHelper.java:62) ~[PassiveSkillTree-1.19.2-BETA-0.5.9.jar%23725!/:0.5.9]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at daripher.skilltree.util.ByteBufHelper.writeAttributeModifiers(ByteBufHelper.java:62) ~[PassiveSkillTree-1.19.2-BETA-0.5.9.jar%23725!/:0.5.9]
	at daripher.skilltree.util.ByteBufHelper.writePassiveSkill(ByteBufHelper.java:76) ~[PassiveSkillTree-1.19.2-BETA-0.5.9.jar%23725!/:0.5.9]
	at daripher.skilltree.util.ByteBufHelper.lambda$writePassiveSkills$2(ByteBufHelper.java:82) ~[PassiveSkillTree-1.19.2-BETA-0.5.9.jar%23725!/:0.5.9]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:?]
	at daripher.skilltree.util.ByteBufHelper.writePassiveSkills(ByteBufHelper.java:82) ~[PassiveSkillTree-1.19.2-BETA-0.5.9.jar%23725!/:0.5.9]
	at daripher.skilltree.network.message.SyncSkillsMessage.encode(SyncSkillsMessage.java:19) ~[PassiveSkillTree-1.19.2-BETA-0.5.9.jar%23725!/:0.5.9]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:121) ~[forge-1.19.2-43.3.0-universal.jar%23852!/:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:119) ~[forge-1.19.2-43.3.0-universal.jar%23852!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:134) ~[forge-1.19.2-43.3.0-universal.jar%23852!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68) ~[forge-1.19.2-43.3.0-universal.jar%23852!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81) ~[forge-1.19.2-43.3.0-universal.jar%23852!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112) ~[forge-1.19.2-43.3.0-universal.jar%23852!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107) ~[forge-1.19.2-43.3.0-universal.jar%23852!/:?]
	at daripher.skilltree.capability.skill.PlayerSkillsProvider.syncSkills(PlayerSkillsProvider.java:59) ~[PassiveSkillTree-1.19.2-BETA-0.5.9.jar%23725!/:0.5.9]
	at daripher.skilltree.capability.skill.__PlayerSkillsProvider_syncSkills_PlayerLoggedInEvent.invoke(.dynamic) ~[PassiveSkillTree-1.19.2-BETA-0.5.9.jar%23725!/:0.5.9]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:774) ~[forge-1.19.2-43.3.0-universal.jar%23852!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:246) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23847!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by SiverDX** [comment]
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/22003703/9851ca1a-5910-4116-a83a-01ba814b9f80)

**Comment by Daripher** [comment]
Are you using any datapacks for the mod? If so, they need to be remade after the last update

**Comment by SiverDX** [comment]
Not knowingly (esp. since I just recently added the mod)
The only usage of `evasion_chance` comes from this mod

**Comment by Baenjamin** [comment]
Getting the same error with the latest version: 0.5.9. 

I also don't have any datapacks, and have not changed any of the config except how much xp is required to buy a skill point. Hmmm.

I tried to delete the config file and got a new one. Not sure if that would do anything. But it still logged me out to the multiplayer menu whenever i tried to either join one of my existing singleplayer worlds. Or whenever i tried to create a fresh one.

Reverting to prior version did make my world playable again. So definetly something funky going on: Sadly, im not a coder or whatever, so i have literally no clue bout whats wrong anyway B)

Love the mod nevertheless tho! 

[latest.log](https://github.com/Daripher/Passive-Skill-Tree/files/12752253/latest.log)

**Comment by SiverDX** [comment]
The modifiers are already broken for all skills when you read them in SkillsReloader
Seems like it cant properly resolve `private List<Pair<Attribute, AttributeModifier>> attributeModifiers = new ArrayList();`

The JSON is the one you provide

**Comment by Daripher** [comment]
> Seems like it cant properly resolve `private List<Pair<Attribute, AttributeModifier>> attributeModifiers = new ArrayList();`

I think the reason is Operation is an Enum and its names are obfuscated.

**Comment by Daripher** [comment]
Actually now that I think about it everything is goddamn obfuscated in the AttributeModifier class

**Comment by SiverDX** [comment]
i see you previously did it through your JsonHelper, explains why it was working then

**Comment by Daripher** [comment]
I think Gson serialization is much cleaner, I'll just need to write a serializer for AttributeModifier objects.

**Comment by SiverDX** [comment]
guess you could copy what mojang is doing

https://github.com/NikitaCartes-archive/MinecraftDeobfuscated-Mojang/blob/1.19.2/net/minecraft/world/item/crafting/SimpleCookingSerializer.java

**Comment by Daripher** [comment]
Doesn't see how this code helps. And I've already fixed the issue.
