### ISSUE TITLE
[1.19.2]: Insufficient number of affixes for jewelry

### ISSUE THREAD

**Issue by SiverDX** [Daripher/Passive-Skill-Tree#50]
Well I guess Apotheosis does warn you about it

``` log
[01Oct2023 20:11:07.475] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category ringRequired: 2; Provided: 0
[01Oct2023 20:11:07.475] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category necklaceRequired: 2; Provided: 0
[01Oct2023 20:11:07.475] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category ringRequired: 3; Provided: 0
[01Oct2023 20:11:07.475] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category necklaceRequired: 3; Provided: 0
[01Oct2023 20:11:07.475] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category ringRequired: 2; Provided: 0
[01Oct2023 20:11:07.475] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category necklaceRequired: 2; Provided: 0
[01Oct2023 20:11:07.476] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category ringRequired: 3; Provided: 0
[01Oct2023 20:11:07.476] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category necklaceRequired: 3; Provided: 0
[01Oct2023 20:11:07.476] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category ringRequired: 2; Provided: 0
[01Oct2023 20:11:07.476] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category necklaceRequired: 2; Provided: 0
[01Oct2023 20:11:07.476] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category ringRequired: 4; Provided: 0
[01Oct2023 20:11:07.476] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category necklaceRequired: 4; Provided: 0
[01Oct2023 20:11:07.476] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category helmetRequired: 3; Provided: 2
[01Oct2023 20:11:07.476] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category bootsRequired: 3; Provided: 2
[01Oct2023 20:11:07.476] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category ringRequired: 3; Provided: 0
[01Oct2023 20:11:07.476] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category necklaceRequired: 3; Provided: 0
[01Oct2023 20:11:07.477] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category ringRequired: 4; Provided: 0
[01Oct2023 20:11:07.477] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category necklaceRequired: 4; Provided: 0
```

``` log
[01Oct2023 20:45:44.034] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: Failed to locate any affixes for heavy_chain_necklace{null} with category LootCategory[necklace] and rarity LootRarity{uncommon}.
	at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:71) ~[Apotheosis-1.19.2-6.4.0.jar%23516!/:6.4.0]
	at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:40) ~[Apotheosis-1.19.2-6.4.0.jar%23516!/:6.4.0]
	at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:37) ~[Apotheosis-1.19.2-6.4.0.jar%23516!/:6.4.0]
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.19.2-43.3.0-universal.jar%23860!/:?]
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1320) ~[forge-1.19.2-43.3.0-universal.jar%23860!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.valhelsia.valhelsia_core.common.loot.modifiers.AppendLootTableModifier.doApply(AppendLootTableModifier.java:53) ~[valhelsia_core-forge-1.19.2-0.5.0.jar%23830!/:1.19.2-0.5.0]
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.19.2-43.3.0-universal.jar%23860!/:?]
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1320) ~[forge-1.19.2-43.3.0-universal.jar%23860!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_79123_(LootTable.java:110) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.m_59640_(RandomizableContainerBlockEntity.java:82) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.m_8020_(RandomizableContainerBlockEntity.java:99) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.Containers.m_18986_(Containers.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.Containers.m_19002_(Containers.java:14) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.level.block.ChestBlock.m_6810_(ChestBlock.java:222) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60753_(BlockBehaviour.java:690) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:240) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.level.Level.m_6933_(Level.java:211) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.level.Level.m_7731_(Level.java:188) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_230328_(StructureTemplate.java:236) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.thirdlife.iterrpg.procedures.GenericDungeonSpawnProcedure.execute(GenericDungeonSpawnProcedure.java:175) ~[iterpg-0.4.8.jar%23670!/:?]
	at net.thirdlife.iterrpg.block.GenericDungeonGenBlockBlock.m_213897_(GenericDungeonGenBlockBlock.java:70) ~[iterpg-0.4.8.jar%23670!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222963_(BlockBehaviour.java:694) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:645) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:276) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23855!/:?]
	... 5 more
```

**Comment by SiverDX** [comment]
Adding a singular dummy affix would solve the issue since the exception just checks if the number of affixes is 0 when creating the item
